package recorder

import (
	as "github.com/godevsig/adaptiveservice"
)

// SessionRequest is the message sent by client.
// Return SessionResponse.
// Client should send one or more Record after SessionResponse is received.
type SessionRequest struct {
	Tag string
}

// SessionResponse is the message replied by server.
type SessionResponse struct {
	RecorderURL string
}

func init() {
	as.RegisterType((*SessionRequest)(nil))
	as.RegisterType((*SessionResponse)(nil))
}

//go:generate mkdir -p $GOPACKAGE
//go:generate sh -c "echo '// Code generated by original messages.go. DO NOT EDIT.\n' > $GOPACKAGE/$GOFILE"
//go:generate sh -c "grep -v go:generate $GOFILE >> $GOPACKAGE/$GOFILE"
//go:generate gopls format -w $GOPACKAGE/$GOFILE
//go:generate git add $GOPACKAGE/$GOFILE
