package plantuml

import (
	as "github.com/godevsig/adaptiveservice"
)

// PlantRequest is the message sent by client.
// Return ChassisModelResponse.
type PlantRequest struct {
	Tag  string `json:"tag"`
	Data string `json:"data"`
}

// PlantResponse is the message replied by the server.
type PlantResponse struct {
	URL string `json:"url"`
}

func init() {
	as.RegisterType((*PlantRequest)(nil))
	as.RegisterType((*PlantResponse)(nil))
}

//go:generate mkdir -p $GOPACKAGE
//go:generate sh -c "echo '// Code generated by original messages.go. DO NOT EDIT.\n' > $GOPACKAGE/$GOFILE"
//go:generate sh -c "grep -v go:generate $GOFILE >> $GOPACKAGE/$GOFILE"
//go:generate gofmt -w $GOPACKAGE/$GOFILE
//go:generate git add $GOPACKAGE/$GOFILE
